services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=test'
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
